architecture: dense
training_parameters:
  batch_size: 10000
  batch_buffer_size: 100
  train_size: 0.7
  scale_features: standard
  shuffle: true
validation_parameters:
  batch_size: 10000
  batch_buffer_size: 100
  scale_features: standard
  shuffle: true
weight_expression: weight_total*xs/sumw
features:
- mjj
- dphijj
- detajj
- mjj_maxmjj
- dphijj_maxmjj
- detajj_maxmjj
- recoil_pt
- dphi_ak40_met
- dphi_ak41_met
- ht
- leadak4_pt
- leadak4_eta
- trailak4_pt
- trailak4_eta
- leadak4_mjjmax_pt
- leadak4_mjjmax_eta
- trailak4_mjjmax_pt
- trailak4_mjjmax_eta
arch_parameters:
  n_features: 18
  n_classes: 2
  n_nodes: [18,18,10,10,5,2]
  dropout: 0.2
